// <auto-generated />
namespace Garage_2_3_MG_JG_PES.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class ÄndradelängdenförsträngländsminimumNumin3tecken : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ÄndradelängdenförsträngländsminimumNumin3tecken));
        
        string IMigrationMetadata.Id
        {
            get { return "201802131347593_Ändrade längden för strängländsminimum. Nu min=3 tecken."; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
