// <auto-generated />
namespace Garage_2_3_MG_JG_PES.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Seedförslagnr1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Seedförslagnr1));
        
        string IMigrationMetadata.Id
        {
            get { return "201802131559421_Seed förslag nr 1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
